version: '3'

services:
  sioux-admin-website:
    restart: always
    image: sioux-admin-website
    container_name: sioux-admin-website
    build: .
    volumes:
      - "./dist:/usr/share/nginx/html"
    ports:
      - '80:80'
    networks:
      - proxy

networks:
  proxy:
    external:
      name: traefik_proxy
